import { Router } from "express";
import { fullName, readDatabase } from "../db.js";

const router = Router();

// A student-facing feed of what they've been charged. Only revenue
// transactions (posted from the Revenues quick-entry form, or generated by
// a recurring revenue transaction) show up here — expenses and manual
// journal entries are accounting-only and not part of this feed.
router.get("/", async (req, res) => {
  const db = await readDatabase();
  const role = req.user!.role;

  let clientId: string | null = null;
  if (role === "student") {
    clientId = req.user!.clientId;
    if (!clientId) return res.json([]);
  } else if (req.query.clientId) {
    clientId = String(req.query.clientId);
  }

  const accountsById = new Map(db.accounts.map((a) => [a.id, a]));
  const clientsById = new Map(db.clients.map((c) => [c.id, c]));

  let entries = db.journalEntries.filter((je) => je.source === "revenue" && je.clientId);
  if (clientId) entries = entries.filter((je) => je.clientId === clientId);

  const activity = entries
    .map((je) => {
      const revenueLine = je.lines.find((l) => l.credit > 0);
      const depositLine = je.lines.find((l) => l.debit > 0);
      const amount = revenueLine?.credit || depositLine?.debit || 0;
      const account = revenueLine ? accountsById.get(revenueLine.accountId) : undefined;
      const client = je.clientId ? clientsById.get(je.clientId) : undefined;
      return {
        id: je.id,
        date: je.date,
        memo: je.memo,
        reference: je.reference,
        amount,
        accountName: account?.name ?? "",
        clientId: je.clientId as string,
        studentName: client ? fullName(client) : "Unknown",
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date) || b.reference.localeCompare(a.reference));

  res.json(activity);
});

export default router;
